project 'Test.xcodeproj'

# platform :ios, '9.0'

target 'Test' do
  use_frameworks!
    pod 'Alamofire', '~> 4.2.0'
    pod 'SwiftyJSON'
    pod 'Kingfisher', '~> 3.0’
    pod 'GPVideoPlayer'
    pod 'MBProgressHUD', '~> 1.1.0'
end
